function mmLoadMenus() {
	if (window.mm_menu_departments) return;
	window.mm_menu_newsandevents = new Menu("root",279,19,"Verdana, Arial, Helvetica, sans-serif",10,"#000000","#ffffff","#cccccc","#002b5f","left","middle",3,0,500,-5,7,true,true,true,0,true,true);
window.mm_menu_directory = new Menu("root",129,19,"Verdana, Arial, Helvetica, sans-serif",10,"#000000","#ffffff","#cccccc","#002b5f","left","middle",3,0,500,-5,7,true,true,true,0,true,true);
window.mm_menu_about = new Menu("root",87,19,"Verdana, Arial, Helvetica, sans-serif",10,"#000000","#ffffff","#cccccc","#002b5f","left","middle",3,0,500,-5,7,true,true,true,0,true,true);
window.mm_menu_academics = new Menu("root",165,19,"Verdana, Arial, Helvetica, sans-serif",10,"#000000","#ffffff","#cccccc","#002b5f","left","middle",3,0,500,-5,7,true,true,true,0,true,true);
window.mm_menu_departments = new Menu("root",231,19,"Verdana, Arial, Helvetica, sans-serif",10,"#000000","#ffffff","#cccccc","#002b5f","left","middle",3,0,500,-5,7,true,true,true,0,true,true);
mm_menu_departments.addMenuItem("Biological&nbsp;Sciences", "location='http://web.odu.edu/sci/biology/index.html'");
	mm_menu_departments.addMenuItem("Chemistry&nbsp;and&nbsp;BioChemistry", "location='http://web.odu.edu/webroot/orgs/sci/colsciences.nsf/pages/chembiochem'");
	mm_menu_departments.addMenuItem("Computer&nbsp;Science", "location='http://www.cs.odu.edu/'");
	mm_menu_departments.addMenuItem("Mathematics&nbsp;and&nbsp;Statistics", "location='http://www.math.odu.edu/'");
	mm_menu_departments.addMenuItem("Ocean,&nbsp;Earth&nbsp;&&nbsp;Atmospheric&nbsp;Sciences", "location='http://www.odu.edu/sci/oceanography'");
	mm_menu_departments.addMenuItem("Physics", "location='http://www.physics.odu.edu/'");
	mm_menu_departments.addMenuItem("Psychology", "location='http://sci.odu.edu/psychology'");
	mm_menu_departments.hideOnMouseOut=true;
	mm_menu_departments.bgColor='#555555';
	mm_menu_departments.menuBorder=1;
	mm_menu_departments.menuLiteBgColor='#ffffff';
	mm_menu_departments.menuBorderBgColor='#555555';
	mm_menu_academics.addMenuItem("Undergraduate&nbsp;Degrees", "location='/sci/academics/undergraduatedegrees.shtml'");
	mm_menu_academics.addMenuItem("Graduate&nbsp;Degrees", "location='/sci/academics/graduatedegrees.shtml'");
	mm_menu_academics.addMenuItem("Undergraduate&nbsp;Advising", "location='/sci/academics/undergraduate_advising/'");
	mm_menu_academics.addMenuItem("Programs&nbsp;and&nbsp;Centers", "location='/sci/academics/programs.shtml'");
	mm_menu_academics.addMenuItem("International&nbsp;Dimensions", "location='/sci/academics/internationaldimension.shtml'");
	mm_menu_academics.hideOnMouseOut=true;
	mm_menu_academics.bgColor='#555555';
	mm_menu_academics.menuBorder=1;
	mm_menu_academics.menuLiteBgColor='#ffffff';
	mm_menu_academics.menuBorderBgColor='#555555';
	mm_menu_about.addMenuItem("Mission&nbsp;Statement", "location='/sci/about/information/index.shtml'");
	mm_menu_about.addMenuItem("Student&nbsp;Goals", "location='/sci/about/policies/research_proposal_submission.shtml'");
	mm_menu_about.addMenuItem("Organization", "location='/sci/about/forms/index.shtml'");
	mm_menu_about.addMenuItem("Facilities", "location='/sci/about/forms/index.shtml'");
	
	
	mm_menu_about.hideOnMouseOut=true;
	mm_menu_about.bgColor='#555555';
	mm_menu_about.menuBorder=1;
	mm_menu_about.menuLiteBgColor='#ffffff';
	mm_menu_about.menuBorderBgColor='#555555';
	mm_menu_directory.addMenuItem("Faculty", "location='/sci/directory/facultystaff.shtml'");
	mm_menu_directory.addMenuItem("Staff", "location='/sci/directory/facultystaff.shtml'");
	mm_menu_directory.addMenuItem("Chair", "location='/sci/directory/dean.shtml'");
	mm_menu_directory.addMenuItem("New Faculty", "location='/sci/directory/new_staff.shtml'");
	mm_menu_directory.hideOnMouseOut=true;
	mm_menu_directory.bgColor='#555555';
	mm_menu_directory.menuBorder=1;
	mm_menu_directory.menuLiteBgColor='#ffffff';
	mm_menu_directory.menuBorderBgColor='#555555';
	mm_menu_newsandevents.addMenuItem("Events&nbsp;Calendar", "location='http://jasper.ts.odu.edu/Apps/OCCS/EventsCalendar.nsf/ESciences?OpenView&Grid=4'");
	mm_menu_newsandevents.addMenuItem("Commencement", "location='/sci/news_events/commencement.shtml'");
	mm_menu_newsandevents.addMenuItem("Distinguished&nbsp;Visitor&nbsp;Lecture&nbsp;Series&nbsp;&nbsp;-&nbsp;NEW", "location='/sci/news_events/distinguished-visitor-list.shtml'");
	mm_menu_newsandevents.addMenuItem("SCIRE&nbsp;Newsletter", "location='http://web.odu.edu/webroot/orgs/sci/colsciences.nsf/pages/scire'");
	mm_menu_newsandevents.addMenuItem("Catalyst&nbsp;Magazine", "location='/sci/news_events/catalyst.shtml'");
	mm_menu_newsandevents.addMenuItem("Departmental&nbsp;Seminar&nbsp;Series", "location='/sci/news_events/departmental_series.shtml'");
	mm_menu_newsandevents.addMenuItem("Featured&nbsp;Alumni", "location='/sci/news_events/featured_alumni/richard.shtml'");
	mm_menu_newsandevents.hideOnMouseOut=true;
	mm_menu_newsandevents.bgColor='#555555';
	mm_menu_newsandevents.menuBorder=1;
	mm_menu_newsandevents.menuLiteBgColor='#ffffff';
	mm_menu_newsandevents.menuBorderBgColor='#555555';
	mm_menu_departments.writeMenus();
}